// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DestroyableController from "./destroyable_controller"
application.register("destroyable", DestroyableController)

import FormController from "./form_controller"
application.register("form", FormController)

import MotifFormController from "./motif_form_controller"
application.register("motif-form", MotifFormController)

import PrintController from "./print_controller"
application.register("print", PrintController)

import RdvPlanController from "./rdv_plan_controller"
application.register("rdv-plan", RdvPlanController)