require:
  - rubocop-rspec
  - rubocop-rails

AllCops:
  Exclude:
    - "vendor/bundle/**/*"
    - "bin/*"
    - "node_modules/**/*"
    - 'db/schema.rb'
  NewCops: enable
  TargetRubyVersion: 3.0.2

Bundler/OrderedGems:
  Exclude:
    - 'Gemfile'

Layout/LineLength:
  Max: 200

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Lint/MissingSuper:
  Exclude:
    - 'app/services/**/*' # Inheriting BaseService without calling super is OK.

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "Guardfile"
    - "scripts/*"
    - "spec/**/*"
    - "config/initializers/*"
    - "config/environments/*"
    - "config/routes.rb"

Metrics/CyclomaticComplexity:
  Max: 8 # default is 7

Metrics/ClassLength:
  Max: 150
  CountAsOne: ['array', 'hash', 'heredoc']
  Exclude:
    - 'app/models/user.rb'

Metrics/MethodLength:
  CountAsOne: ['array', 'hash', 'heredoc']
  Max: 20
  Exclude:
    - 'db/migrate/20210301135256_create_territories.rb'

Rails/ApplicationController:
  Exclude:
    - 'app/controllers/api/v1/base_controller.rb'

Rails/CreateTableWithTimestamps:
  Exclude:
    - 'db/migrate/20210301135256_create_territories.rb'

Rails/DynamicFindBy:
  Exclude:
    - 'spec/features/agents/admin_can_configure_the_organisation_spec.rb'

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/RakeEnvironment:
  Exclude:
    - 'lib/tasks/matomo.rake'

Rails/SkipsModelValidations:
  Exclude:
    - 'scripts/agent_et_motif_changent_de_service.rb'
    - 'db/migrate/20210301135256_create_territories.rb'
    - 'app/models/user.rb'
    - 'app/models/concerns/expiration.rb'
    - 'app/models/motif.rb'
    - 'app/models/agent.rb'
    - 'scripts/update_city_name_postal_code_and_city_code_from_address.rb'

Rails/LexicallyScopedActionFilter:
  Exclude:
    - 'app/controllers/users/sessions_controller.rb'
    - 'app/controllers/user_auth_controller.rb'
    - 'app/controllers/agents/sessions_controller.rb'
    - 'app/controllers/agent_auth_controller.rb'

RSpec/AnyInstance:
  Exclude:
    - spec/controllers/admin/users_controller_spec.rb
    - spec/controllers/admin/referents_controller_spec.rb

RSpec/ContextWording:
  Enabled: False

RSpec/ExampleLength:
  Max: 30
  Exclude:
    - 'spec/features/**/*'
    - 'spec/requests/api/**/*'

RSpec/LetSetup:
  Enabled: false

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/MultipleDescribes:
  Exclude:
    - 'spec/policies/agent/*_policy_spec.rb'

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

RSpec/DescribeClass:
  Exclude:
    - "spec/features/**/*"

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/CommentedKeyword:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/GuardClause:
  Exclude:
    - 'app/controllers/admin/territories/sms_configurations_controller.rb'
