require:
  - rubocop-rspec
  - rubocop-rails

AllCops:
  Exclude:
    - "vendor/bundle/**/*"
    - "bin/*"
    - "node_modules/**/*"
    - 'db/schema.rb'
  NewCops: enable
  TargetRubyVersion: 3.1.2

Bundler/OrderedGems:
  Exclude:
    - 'Gemfile'

Layout/LineLength:
  Max: 200

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Lint/MissingSuper:
  Exclude:
    - 'app/services/**/*' # Inheriting BaseService without calling super is OK.

Lint/AssignmentInCondition:
  Exclude:
    - 'db/migrate/20211215182150_add_service_name_to_active_storage_blobs.active_storage.rb'

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "Guardfile"
    - "scripts/*"
    - "spec/**/*"
    - "config/initializers/*"
    - "config/environments/*"
    - "config/routes.rb"

Metrics/CyclomaticComplexity:
  Max: 8 # default is 7

Metrics/ClassLength:
  Max: 150
  CountAsOne: ['array', 'hash', 'heredoc']
  Exclude:
    - 'app/models/rdv.rb'
    - 'app/models/user.rb'

Metrics/ModuleLength:
  Max: 150
  CountAsOne: ['array', 'hash', 'heredoc']

Metrics/MethodLength:
  CountAsOne: ['array', 'hash', 'heredoc']
  Max: 20
  Exclude:
    - 'db/migrate/20210301135256_create_territories.rb'

Rails/ApplicationController:
  Exclude:
    - 'app/controllers/api/v1/base_controller.rb'
    - 'app/controllers/api/v1/agent_auth_base_controller.rb'

Rails/CreateTableWithTimestamps:
  Exclude:
    - 'db/migrate/20210301135256_create_territories.rb'
    - 'db/migrate/20211215182151_create_active_storage_variant_records.active_storage.rb'

Rails/DynamicFindBy:
  Enabled: false

Rails/FilePath:
  Exclude:
    - 'config/environments/development.rb'

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/RakeEnvironment:
  Exclude:
    - 'lib/tasks/matomo.rake'

Rails/SkipsModelValidations:
  Exclude:
    - 'scripts/agent_et_motif_changent_de_service.rb'
    - 'db/migrate/20210301135256_create_territories.rb'
    - 'app/models/user.rb'
    - 'app/models/rdv.rb'
    - 'app/models/concerns/expiration.rb'
    - 'app/models/motif.rb'
    - 'app/models/agent.rb'
    - 'scripts/update_city_name_postal_code_and_city_code_from_address.rb'
    - 'db/migrate/*.rb'

Rails/LexicallyScopedActionFilter:
  Exclude:
    - 'app/controllers/users/sessions_controller.rb'
    - 'app/controllers/user_auth_controller.rb'
    - 'app/controllers/agents/sessions_controller.rb'
    - 'app/controllers/agent_auth_controller.rb'

Rails/ActiveRecordCallbacksOrder:
  Enabled: false

# This allows the standard syntax for the `change` matcher, see:
# https://relishapp.com/rspec/rspec-expectations/docs/built-in-matchers/change-matcher
Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'

RSpec/AnyInstance:
  Exclude:
    - spec/controllers/admin/users_controller_spec.rb
    - spec/controllers/admin/referent_assignations_controller_spec.rb
    - spec/controllers/users/rdvs_controller_spec.rb
    - spec/features/users/user_can_be_invited_spec.rb

RSpec/DescribedClass:
  Exclude:
    - spec/controllers/concerns/token_invitable_spec.rb

RSpec/ContextWording:
  Enabled: False

RSpec/ExampleLength:
  Max: 30
  Exclude:
    - 'spec/features/**/*'
    - 'spec/requests/api/**/*'

RSpec/LetSetup:
  Enabled: false

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/MultipleDescribes:
  Exclude:
    - 'spec/policies/agent/*_policy_spec.rb'

RSpec/VariableName:
  Exclude:
    - "spec/requests/api/v1/**/*"
    - "spec/support/api_spec_shared_examples.rb"

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

RSpec/DescribeClass:
  Exclude:
    - "spec/features/**/*"
    - "spec/requests/**/*"
    - "spec/sms/**/*"

RSpec/RepeatedExample:
  Exclude:
    - "spec/requests/api/**/*"

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/CommentedKeyword:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - "config/**/*"
    - "config.ru"

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/OpenStructUse:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/DateTime:
  Enabled: true

Naming/BlockForwarding:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
  Exclude:
    - "config/**/*"

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

RSpec/ScatteredSetup:
  Enabled: false
