nodeLinker: node-modules

enableScripts: false

# On ajoute un temps de quarantaine pour éviter d’installer des paquets trop rapidement après leur publication dans
# le but de réduire les risques liés à des paquets malveillants (comme avec Shai Hulud).
npmMinimalAgeGate: 43200 # 30 jours
