nodeLinker: node-modules

supportedArchitectures:
  os: ["linux", "darwin", "current"]
  cpu: ["x64", "arm64", "current"]

enableScripts: false

# On ajoute un temps de quarantaine pour éviter d’installer des paquets trop rapidement après leur publication dans
# le but de réduire les risques liés à des paquets malveillants (comme avec Shai Hulud).
npmMinimalAgeGate: 5760 # 4 jours

enableGlobalCache: false
cacheFolder: .yarn/cache
