nodeLinker: node-modules

supportedArchitectures:
  os: ["linux", "darwin", "current"]
  cpu: ["x64", "arm64", "current"]

enableScripts: false

# On ajoute un temps de quarantaine pour éviter d’installer des paquets trop rapidement après leur publication dans
# le but de réduire les risques liés à des paquets malveillants (comme avec Shai Hulud).
#
# Note : Pour mettre une lib à jour en urgence, il faut bypass cette valeur à l'aide d'une variable d'ENV :
# > YARN_NPM_MINIMAL_AGE_GATE=0 yarn up -R nom_de_la_lib
#
npmMinimalAgeGate: 5760 # 4 jours
