# PostgreSQL. Versions 9.1 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On OS X with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On OS X with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
default: &default
  adapter: postgresql
  encoding: unicode
  <% if ENV['POSTGRES_USER'].present? %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['POSTGRES_HOST'] %>
  <% end %>
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  # And also GoodJob doc: https://github.com/bensheldon/good_job#database-connections
  #
  # Pour les containers web, on ouvre une connexion par thread puma.
  # On utilise `load_async` à certains endroits, ce qui veut dire qu'un thread peut utiliser plusieurs connexions à la fois (voir global_executor_concurrency).
  # Dans le scénario du pire, il est possible que tous les thread soient en train d'accéder à la base de données, et que certains d'entre eux soient en plus en train d'exécuter du code qui utilise `load_async`. Cependant, ce cas ne se produit jamais ou quasiment jamais. S'il a lieu, les thread attendront d'avoir une connexion disponible, ce qui peut causer un ralentissement de l'application, mais probablement pas assez pour générer un timeout.
  # Les connexions ont un cout au niveau du server de base de données : chaque connexion utilise de la RAM, donc on essaye de ne pas trop en ouvrir.
  # Pour savoir combien de connexions on utilise, on peut vérifier sur Scalingo via la page "Running queries" du dashboard postgres
  # par exemple https://dashboard.scalingo.com/apps/osc-secnum-fr1/production-rdv-solidarites/db/postgresql/running-queries
  #
  # On pourrait même mieux utiliser le mécanisme de connection pool, et avoir moins de connexions que de threads.
  #
  # For GoodJob container, we need connections for :
  # - the max number of threads (5 by default, cf https://github.com/bensheldon/good_job/blob/main/lib/good_job/configuration.rb#L126-L134)
  # - LISTEN/NOTIFY, cron etc (2 cf https://github.com/bensheldon/good_job?tab=readme-ov-file#database-connections)
  # - multithreaded database queries, e.g. load_async (1 cf https://github.com/bensheldon/good_job?tab=readme-ov-file#database-connections)
  #
  # cf docs/4-notes-techniques.md pour une vue d’ensemble du nombre de threads et de connexions à
  # la base de données
  pool: <%= $PROGRAM_NAME.include?("good_job") ? GoodJob.configuration.max_threads + 2 + 1 : (ENV.fetch("RAILS_MAX_THREADS", 4).to_i) %>

development:
  <<: *default
  collation: en_US.UTF-8 # pour être raccord avec la config sur Scalingo
  ctype: en_US.UTF-8
  template: template0 # cette base est immutable sur Postgresql v16+
  database: <%= ENV['LAPIN_DATABASE_NAME'] || "lapin_development" %>

test:
  <<: *default
  collation: en_US.UTF-8 # pour être raccord avec la config sur Scalingo
  ctype: en_US.UTF-8
  template: template0 # cette base est immutable sur Postgresql v16+
  database: lapin_test<%= ENV['TEST_ENV_NUMBER'] %>

production:
  <<: *default
  database: lapin_production
  username: lapin
  password: <%= ENV['LAPIN_DATABASE_PASSWORD'] %>
