# rails runner scripts/create_good_job_cron_json.rb

Rails.root.glob("app/jobs/cron_job/**/*").to_a.each { require_relative _1 }

rules_gathered = CronJob.subclasses
  .select { |job_class| job_class.const_defined?("CRON") }
  .sort_by(&:to_s)
  .to_h do |job_class|
  [
    job_class.to_s.split("::").last.underscore,
    { "class" => job_class.to_s, "cron" => job_class::CRON },
  ]
end

path = "config/initializers/good_job_cron.json"
rules_existing = JSON.parse(File.read(path)).except("_comment")
if rules_existing == rules_gathered
  puts "nothing changed, leaving #{rules_existing.count} unchanged rules in #{path}"
elsif ENV["FAIL_UNLESS_UNCHANGED"]
  exit 1
else
  Rails.logger.info <<~MSG
    Rappel des changements d'heure :
    - au passage à l'heure d'hiver, on passe deux fois sur l'heure entre 02:00 et 02:59
    - au passage à l'heure d'été, on passe de 01:59 à 03:00
    Il est donc dangereux de déclarer un cron entre 02:00 et 02:59.
  MSG
  rules_with_comment = { _comment: "THIS FILE IS GENERATED BY scripts/create_good_job_json.rb DO NOT CHANGE MANUALLY" }
    .merge(rules_gathered)
  Rails.root.join(path).write(JSON.pretty_generate(rules_with_comment))
  puts "wrote #{rules_gathered.count} rules to #{path}"
end
