name: Setup Playwright
runs:
  using: composite
  steps:
    - name: Cache Playwright Chromium browser
      id: playwright-cache
      uses: actions/cache@v4
      with:
        path: ~/.cache/ms-playwright
        key: playwright-browsers-${{ runner.os }}-${{ hashFiles('yarn.lock') }}-v3
    - name: Install Playwright Chromium browser (with deps)
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      run: yarn run playwright install chromium --only-shell
      shell: bash
