name: Pull Requests Reminder
on:
  push:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:


jobs:
  pull-request-reminder:
    runs-on: ubuntu-latest
    steps:
      - name: Pull requests reminder
        uses: davideviolante/pr-reviews-reminder-action@v2.8.0
        env:
          GITHUB_TOKEN: ${{ secrets.PR_REMINDER_GH_TOKEN }}
        with:
          webhook-url: ${{ secrets.PR_REMINDER_WEBHOOK_URL }}
          provider: slack
          channel: "@adipasquale"
