name: Push docker image from tag
on: 
  push: 
    tags:
      - ^[0-9]+-[0-9]+-[0-9]+-[0-9]+-[0-9]+-[0-9]+-deploy-recette-to-production
# Env variable
env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  DOCKER_REPO_NAME: ${{secrets.DOCKER_REPO_NAME}}
  WEBAPP_DOCKERFILE: ./docker/web/Dockerfile
  JOB_DOCKERFILE: ./docker/job/Dockerfile
jobs:
  push-image:  # job name
    runs-on: ubuntu-latest  # runner name : (ubuntu latest version)
    environment: lapin-beta-gouv
    steps:
    - uses: actions/checkout@v2 # first action : checkout source code

    - name: docker login
      run: | # log into docker registry account
        docker login $DOCKER_REPO_NAME -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Build the Webapp Docker image
      run: docker build . --file $WEBAPP_DOCKERFILE --tag $DOCKER_REPO_NAME/webapp:$GITHUB_REF_NAME
    - name: Docker Push Webapp image
      run: docker push $DOCKER_REPO_NAME/webapp:$GITHUB_REF_NAME
    - name: Build the Job Docker image
      run: docker build . --file $JOB_DOCKERFILE --tag $DOCKER_REPO_NAME/jobs:$GITHUB_REF_NAME
    - name: Docker Push Job image
      run: docker push $DOCKER_REPO_NAME/jobs:$GITHUB_REF_NAME
    - name: Build the Script Docker image
      run: docker build . --file $SCRIPT_DOCKERFILE --tag $DOCKER_REPO_NAME/script:$GITHUB_REF_NAME
    - name: Docker Push Script image
      run: docker push $DOCKER_REPO_NAME/script:$GITHUB_REF_NAME